#!/bin/bash
(
	set -eo pipefail
	[ -z "${DEBUG:-}" ] || set -x
	if [ -v BASH_SOURCE ]; then
		__filename="${BASH_SOURCE[0]}"
	else
		#FIXME: shfmt workaround
		eval '__filename="${(%):-%x}"'
	fi
	__filename="$(realpath -m "${__filename}")"
	__dirname="$(dirname "${__filename}")"
	readonly __filename
	readonly __dirname
	cd "${__dirname}" || exit 1
	cd .. || exit 1

	shfmt -l -w .

	exit 0
)
